version: 2.1

# Keep this at the top to reduce noise in chatrooms when we mess up circleci setup
experimental:
  notify:
    branches:
      only:
        - master

orbs:
  aws-cli: circleci/aws-cli@0.1.16
  linter: thekevjames/linter@1.0.49

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: prettier
          command: npm run prettier:check
      - run:
          name: Run tests
          command: npm test
  deploy-to-s3:
    parameters:
      bucket-name:
        type: string
    machine:
      enabled: true
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Deploy to s3 bucket
          command: |
            if [ "$CIRCLE_REPOSITORY_URL" = "git@github.com:launchdarkly/integration-framework-private.git" ]; then
              ./scripts/copy_to_s3.sh
            fi
          environment:
            BUCKET_NAME: << parameters.bucket-name >>

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - linter/pre-commit:
          config_file: .circleci/.pre-commit-ci.yaml
      - build
      - deploy-to-s3:
          requires:
            - build
          filters:
            branches:
              only: master
          bucket-name: integrations-stg.launchdarkly.com
      - deploy-to-s3:
          requires:
            - build
          filters:
            branches:
              only: deploy-catamorphic
          bucket-name: launchdarkly-integrations-catamorphic
      - deploy-to-s3:
          requires:
            - build
          filters:
            branches:
              only: deploy-production
          bucket-name: launchdarkly-integrations-production
