version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - aws-cli/install
      - deploy:
          command: |
            npm ci &&
            npm test &&
            ./scripts/copy_to_s3.sh
