version: 2.1

# Keep this at the top to reduce noise in chatrooms when we mess up circleci setup
experimental:
  notify:
    branches:
      only:
        - master

orbs:
  aws-cli: circleci/aws-cli@0.1.16
  linter: thekevjames/linter@1.0.49

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: prettier
          command: npm run prettier:check
      - run:
          name: Run tests
          command: npm test
  upload-to-s3:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Upload artifacts to s3
          command: |
            if [ "$CIRCLE_REPOSITORY_URL" = "git@github.com:launchdarkly/integration-framework-private.git" ]; then
              ./scripts/upload_artifacts_to_s3.sh
            fi
  send-webhook:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: send-webhook
          command: |
            if [ "$CIRCLE_REPOSITORY_URL" = "git@github.com:launchdarkly/integration-framework-private.git" ]; then
              ./scripts/send_webhook.sh
            fi

workflows:
  build-and-deploy:
    jobs:
      - linter/pre-commit:
          config_file: .circleci/.pre-commit-ci.yaml
      - build
      - upload-to-s3:
          requires:
            - build
          context: org-global
          filters:
            branches:
              only: master
      - send-webhook:
          requires:
            - build
