version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm test
  deploy-to-s3:
    machine:
      enabled: true
    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Deploy to production bucket
          command: ./scripts/copy_to_s3.sh
          environment:
            BUCKET_NAME: launchdarkly-integrations-production
      - run:
          name: Deploy to staging bucket
          command: ./scripts/copy_to_s3.sh
          environment:
            BUCKET_NAME: launchdarkly-integrations-staging
      - run:
          name: Deploy to catfood bucket
          command: ./scripts/copy_to_s3.sh
          environment:
            BUCKET_NAME: launchdarkly-integrations-catamorphic

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy-to-s3:
          requires:
            - build
          filters:
            branches:
              only: master
