name: Copy repo to S3

on:
  push:
    branches: 
      - master
jobs:
  s3copy:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master
    - name: S3 Backup
      uses: peter-evans/s3-backup@v1.0.0
      env:
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        MIRROR_TARGET: launchdarkly-integrations-dev/integrations
      with:
        args: --overwrite --remove
